name: Belajar CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  belajar:
    name: Test CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Perintah Linux
        run: |
          git status
          ls -lah
          id
          echo "Hery is here"